# This is a basic workflow to help you get started with Actions

name: CD for Heroku Deployment

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the develop branch
    push:
        branches:
            - feature/createEvent

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        # The type of runner that the job will run on
        runs-on:
            ubuntu-latest

            # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                  ref: feature/createEvent
            - name: Update Heroku
              run: sudo apt update && sudo apt install heroku

            # Runs a single command using the runners shell
            - name: Login to Heroku Container registry
              run: heroku container:login
